[package]
name = "scribe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
crossterm = "0.28.1"
nix = { version = "0.29.0", features = ["signal"] }
